Strip new lines in argLine and debugArgLine parameters
scalatest/scalatest-maven-plugin pull request #77
Opened 2020-08-08 23:44 UTC by veysiertekin

Formatters sometime causes new lines in `pom.xml` files:

```
        <argLine>-Xms4g -Xmx4g -XX:MaxPermSize=512m -XX:MaxDirectMemorySize=10g
          -Dlog4j2.configurationFile=log4j2-fatal-only.xml
        </argLine>
```

This result in failures at java cmd command execution:

```
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ test-project ---
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
                  The default VM is server,
                  because you are running on a server-class machine.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
/bin/sh: line 1: -Dlog4j2.configurationFile=log4j2-fatal-only.xml: command not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.805 s
[INFO] Finished at: 2020-08-09T02:39:43+03:00
```

This PR addresses this issue and allows developers to use multi line JVM parameters.

For an instance, `maven-surefire-plugin` also have a fix for this:

https://github.com/apache/maven-surefire/blob/eb48f1b59ca5ccf6954ef33ecab03dbaf93214cd/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/DefaultForkConfiguration.java#L246-L249

2020-08-08 23:50 UTC, artimasites commented
@cla-bot[bot] check

2020-09-20 19:13 UTC, katrinsharp requested changes
Could you please add a test with a command line arguments without new lines, i.e. 
"-Xms4g -Xmx4g -XX:MaxPermSize=512m"? Thank you.

2020-09-20 19:14 UTC, katrinsharp commented
Hi Veysi, thank you for submitting you PR. Please see my comment.

2020-09-21 06:34 UTC, veysiertekin commented
hi @katrinsharp ,
I have added a few new test cases for command lines without or parttially have new lines.

2020-10-10 01:15 UTC, merged